### ISSUE TITLE
Profile Page Cannot Load Static Files | Importance * * * * *

### ISSUE THREAD

**Issue by devojoyti** [markroxor/Roboism#13]
After user login, profile page is not able to load user profile, although correct credentials like username, name etc. are passed by django. But, the values are not showing.

![noprofile](https://cloud.githubusercontent.com/assets/19840930/16340809/a3bdb110-3a47-11e6-92ce-9865fe9957de.png)

**Comment by devojoyti** [comment]
mistake rectified in commit 1c5cf86

**Comment by markroxor** [comment]
@devojoyti  mention commit.
